CREATE TABLE IF NOT EXISTS nutritionists (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dishes (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  calories_per_100 DECIMAL(10,2),
  proteins_per_100 DECIMAL(10,2),
  carbs_per_100 DECIMAL(10,2),
  fats_per_100 DECIMAL(10,2),
  instruction TEXT,
  video_url VARCHAR(255),
  image_url VARCHAR(255),
  unit VARCHAR(10) DEFAULT 'г',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS meal_items (
  id INT PRIMARY KEY AUTO_INCREMENT,
  block_id INT NOT NULL,
  dish_id INT NOT NULL,
  amount DECIMAL(10,2),
  note TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (block_id) REFERENCES meal_blocks(id) ON DELETE CASCADE,
  FOREIGN KEY (dish_id) REFERENCES dishes(id) ON DELETE CASCADE
);

-- Добавить поле unit для dish_ingredients
ALTER TABLE dish_ingredients ADD COLUMN unit VARCHAR(10) DEFAULT 'г'; 